# Generated by Django 2.2.6 on 2020-01-03 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('stores', models.ManyToManyField(to='main_app.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='cleaning date')),
                ('time', models.CharField(choices=[('8', '8:00am'), ('9', '9:00am'), ('10', '10:00am'), ('11', '11:00am'), ('12', '12:00pm'), ('1', '1:00pm'), ('2', '2:00pm'), ('3', '3:00pm'), ('4', '4:00pm'), ('5', '5:00pm')], max_length=1)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Shoe')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
